apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox1
  labels:
    app: busybox1
    project: oam-service-binding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox1
  template:
    metadata:
      name: busybox1
      labels:
        app: busybox1
    spec:
      containers:
        - name: busybox1
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "printenv; sleep 6000"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox2
  labels:
    app: busybox2
    project: oam-service-binding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox2
  template:
    metadata:
      name: busybox2
      labels:
        app: busybox2
    spec:
      containers:
        - name: busybox2
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "printenv; sleep 6000"]
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: YWJj # abc
  password: MTIz # 123
